### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by hanhaotian** [salamer/Zhihu_Crawler#2]
不知道你能看到不，一直卡在这个问题上。如果有时间就帮忙解答下哦。谢谢啦！

Traceback (most recent call last):
  File "F:/Zhihu_Crawler-master/multi_threading.py", line 56, in <module>
    create_new_slave(url, option=option)
  File "F:/Zhihu_Crawler-master/multi_threading.py", line 19, in create_new_slave
    new_slave.send_request()
  File "F:\Zhihu_Crawler-master\thread_crawler.py", line 52, in send_request
    added_followee_url = self.url + "/followees"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

added_followee_url = self.url + "/followees"

是这里有问题嘛？

**Comment by maicWorkGithub** [comment]
你的URL是什么？这个问题的url。
这个的意思是当前url是空的，未赋值。

**Comment by maicWorkGithub** [comment]
很奇怪啊，这个ISSUE为啥会邮件通知我？我也不是贡献者也不是开发者~~~醉了

**Comment by hanhaotian** [comment]
呃，缘分呐！哈哈，  crawler.py里的self.url = url
engine.py里的  red.lpush(red_queue, "https://www.zhihu.com/people/gaoming623")

都没动过，确实不知道这个self.url该设置成什么，请大神指点一二

**Comment by hanhaotian** [comment]
D:\WorkPlace\python2\python.exe F:/Zhihu_Crawler-master/engine.py
https://www.zhihu.com/people/gaoming623            self.url的print

---

用户名:Mingo鸣哥

用户性别:female

用户地址:香港

被同意:77648

被感谢:19444

被关注:51932

关注了:1188

工作:记者/
教育:香港中文大学 (Chinese University of Hong Kong)/新媒体
用户信息:

---

Traceback (most recent call last):
  File "F:/Zhihu_Crawler-master/engine.py", line 69, in <module>
    create_new_slave(url, option=option)
  File "F:/Zhihu_Crawler-master/engine.py", line 23, in create_new_slave
    new_slave.send_request()
  File "F:\Zhihu_Crawler-master\crawler.py", line 57, in send_request
    added_followee_url = self.url + "/followees"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Process finished with exit code 1

运行后就是这样的结果，也不知道是哪里没对

**Comment by maicWorkGithub** [comment]
我大概看了一下，没看出来是什么问题，你还不会debug吗？
我给你问一下作者吧。
另外，这个项目就是作者拿来玩玩的，应该不会更新了。
要是用的话，你得学会自己修改。

**Comment by hanhaotian** [comment]
好的，谢谢啦！我自己也正在学习ing

**Comment by maicWorkGithub** [comment]
我自己也弄了一个，不过不是并发的，他这个是并发的。
目前还在修改中。

**Comment by hanhaotian** [comment]
pa-zhihu   应该是这个吧，我也在看呢
